# action.yml
name: "Azure Blob Container Deploy"
description: "Deploys files to Azure Storage Blob"
branding:
  icon: "box"
  color: "green"
inputs:
  SOURCE_DIR:
    description: "The name of the directory you want to upload"
    required: true
  DESTINATION_DIR:
    description: "The name of the blob container you want to upload to"
    required: true
  AZURE_SECRET:
    description: "Your Azure Secret"
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: "Your Azure Subscription ID"
    required: true
  AZURE_STORAGE_ACCOUNT_NAME:
    description: "Your Azure Storage Account Name"
    required: true
  AZURE_STORAGE_ACCOUNT_KEY:
    description: "Your Azure Storage Account Key"
    required: true
outputs:
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.SOURCE_DIR }}
    - ${{ inputs.DESTINATION_DIR }}
    - ${{ inputs.AZURE_SECRET }}
    - ${{ inputs.AZURE_SUBSCRIPTION_ID }}
    - ${{ inputs.AZURE_STORAGE_ACCOUNT_NAME }}
    - ${{ inputs.AZURE_STORAGE_ACCOUNT_KEY }}
